server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active : local, default
  application:
    name: MainServer
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: hikari
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true


