spring:
  profiles:
    active : local

---

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active : local, default
  application:
    name: MainServer
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/test
      jdbc-url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: hikari
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect